# Generated by Django 3.1.5 on 2021-01-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnfapp', '0002_auto_20210115_0722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scripts',
            old_name='script_name',
            new_name='document_name',
        ),
        migrations.AddField(
            model_name='scripts',
            name='author_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scripts',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scripts',
            name='script_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
